/** CDN paths for tech logos — Devicon multi-color + Simple Icons fallback. */
const D = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons"
const S = (slug: string) => `https://cdn.simpleicons.org/${slug}`

export function getTechIconUrl(techId: string): string | null {
  const m: Record<string, string> = {
    html5: `${D}/html5/html5-original.svg`,
    css3: `${D}/css3/css3-original.svg`,
    js: `${D}/javascript/javascript-original.svg`,
    ts: `${D}/typescript/typescript-original.svg`,
    react: `${D}/react/react-original.svg`,
    vite: `${D}/vite/vite-original.svg`,
    next: `${D}/nextjs/nextjs-original.svg`,
    tailwind: `${D}/tailwindcss/tailwindcss-original.svg`,
    sass: `${D}/sass/sass-original.svg`,
    styled: S("styledcomponents"),
    bootstrap: `${D}/bootstrap/bootstrap-original.svg`,
    shadcn: S("radixui"),
    router: S("reactrouter"),
    motion: S("framer"),
    i18n: S("i18next"),
    zod: S("zod"),
    rhf: S("reacthookform"),
    node: `${D}/nodejs/nodejs-original.svg`,
    express: `${D}/express/express-original.svg`,
    fastapi: S("fastapi"),
    flask: `${D}/flask/flask-original.svg`,
    php: `${D}/php/php-original.svg`,
    mysql: `${D}/mysql/mysql-original.svg`,
    pg: `${D}/postgresql/postgresql-original.svg`,
    mssql: S("microsoftsqlserver"),
    mongo: `${D}/mongodb/mongodb-original.svg`,
    firebase: `${D}/firebase/firebase-plain.svg`,
    supabase: S("supabase"),
    prisma: `${D}/prisma/prisma-original.svg`,
    rest: S("openapiinitiative"),
    git: `${D}/git/git-original.svg`,
    github: `${D}/github/github-original.svg`,
    docker: `${D}/docker/docker-original.svg`,
    cloudflare: `${D}/cloudflare/cloudflare-plain.svg`,
    coolify: S("coolify"),
    nginx: `${D}/nginx/nginx-original.svg`,
    linux: `${D}/linux/linux-original.svg`,
    winserver: S("windows"),
    python: `${D}/python/python-original.svg`,
    playwright: S("playwright"),
    selenium: S("selenium"),
    minio: S("minio"),
    jwt: S("jsonwebtoken"),
    figma: `${D}/figma/figma-original.svg`,
    three: S("threedotjs"),
    r3f: S("threedotjs"),
    wordpress: S("wordpress"),
    elementor: S("elementor"),
    jquery: S("jquery"),
  }
  return m[techId] ?? null
}
